### PR TITLE
Updated to v1.3.10

### PR DESCRIPTION
**Pull request by vician**
New version release to populate the PR #20 to addon repositories.

### CODE REVIEW

**Comment by vician** [comment]
@cguZZman I guess it would help to get the update into the repositories https://mirrors.kodi.tv/addons/nexus/script.module.clouddrive.common/

Or is there any other required step, please?

**Comment by cguZZman** [comment]
Thanks for the PR. This is the best way to help in this time where I have extremely limited time.
Now we need to do the same for the google and onedrive addons by pointing to the new common module version and increasing the version of both addons.
After that we need to submit the PR to Kodi. I will try to apart a couple of hours this weekend to do it. Or if you can do it, it will be awesome.

**Comment by cguZZman** [comment]
Thanks for submitting the PR to Kodi. I think it will be rejected since their policy is that PR should come from the addon's owner.
Since you know what has to be done and what you are doing, I just added you as a collaborator to this repository. 
So, can you cancel the current PR in Kodi, and submit another from this repo?
The matrix branch is already created. And if I remember correctly, there was a previous change pending to be submitted to kodi, so, probably that will come up in the PR.
Thanks much for the help.

**Comment by vician** [comment]
Thank you for your help. I'm not sure either.
I also don't know how I can create a PR from this repo to https://github.com/xbmc/repo-scripts/ when they don't share Git history.
I saw you were previously doing it from https://github.com/cguZZman/repo-scripts/ or maybe I'm missing something about some repo synchronization.

**Comment by cguZZman** [comment]
You right. It has to come from the repo-script repo. Ok, I will create the PR to refresh my memory and document it. And if you are interested in doing it in a future, let me know.
In the meantime, please close the current PR.
Thanks

**Comment by vician** [comment]
Thank you. Happy to help.

**Pull request merged**
